### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by samuelmr** [maaaikoool/neurio#4]
Hi!

Could you please `npm version` and `npm publish` so that #3 would find its way to the npm registry.

Thanks!

**Comment by maaaikoool** [comment]
Done!

**Comment by samuelmr** [comment]
I updated to 0.4.0 npm package but `lib/client.js` doesn't include `Client.prototype.historySamples`

I have to admit I'm a bit lost with this npm versioning and updating stuff...

Are you sure you published the version with #3 merged?

**Comment by maaaikoool** [comment]
You are right. My bad. Should be ok now (0.4.1)
